name: oecd_unemployment_comparison
version: 1.0.0
config-version: 2
profile: pulse_dataset
model-paths: [models]
models:
  oecd_unemployment_comparison:
    +materialized: external
    +location: "{{ var('external_location') }}"
    +format: parquet
