name: european_emigration_flows
version: 1.0.0
config-version: 2
profile: pulse_dataset
model-paths: [models]
macro-paths: [macros]
models:
  european_emigration_flows:
    +materialized: external
    +location: "{{ var('external_location') }}"
    +format: parquet
