name: french_departement_gdp
version: 1.0.0
config-version: 2
profile: pulse_dataset
model-paths: [models]
seed-paths: [seeds]
seeds:
  french_departement_gdp:
    nuts3_departements:
      +column_types:
        nuts3_code: varchar
        departement_code: varchar
        nuts3_name: varchar
models:
  french_departement_gdp:
    +materialized: external
    +location: "{{ var('external_location') }}"
    +format: parquet
