name: world_demography_age_structure
version: 1.0.0
config-version: 2
profile: pulse_dataset
model-paths: [models]
models:
  world_demography_age_structure:
    +materialized: external
    +location: "{{ var('external_location') }}"
    +format: parquet
