name: french_departement_unemployment
version: 1.0.0
config-version: 2
profile: pulse_dataset
model-paths: [models]
models:
  french_departement_unemployment:
    +materialized: external
    +location: "{{ var('external_location') }}"
    +format: parquet
